name = "klyro-site"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "3a7d786ecf0b37fed098a78df2dfbf2b"

[vars]
KLYRO_API_KEY = "f90cecf50e88091412d6e608eaaebc4491c8a433931e4084112776308bb0e711"

# Service binding to the API Worker
[[services]]
binding = "API_WORKER"
service = "klyro-worker"

[assets]
binding = "ASSETS"
